// Skills organized by category
export const SKILL_CATEGORIES = {
  'Programming Languages': [
    'JavaScript',
    'TypeScript',
    'Python',
    'Java',
    'C++',
    'C#',
    'Go',
    'Rust',
    'Ruby',
    'PHP',
    'Swift',
    'Kotlin',
    'SQL',
    'R',
    'MATLAB',
  ],
  'Frontend Development': [
    'React',
    'Vue.js',
    'Angular',
    'Next.js',
    'Svelte',
    'HTML/CSS',
    'Tailwind CSS',
    'React Native',
    'Flutter',
  ],
  'Backend Development': [
    'Node.js',
    'Django',
    'FastAPI',
    'Spring Boot',
    'Express.js',
    'GraphQL',
    'REST APIs',
    'Microservices',
  ],
  'Data & AI': [
    'Machine Learning',
    'Deep Learning',
    'Data Science',
    'Data Analysis',
    'TensorFlow',
    'PyTorch',
    'Computer Vision',
    'NLP',
    'LLMs/GenAI',
  ],
  'Cloud & Infrastructure': [
    'AWS',
    'Google Cloud',
    'Azure',
    'Docker',
    'Kubernetes',
    'DevOps',
    'CI/CD',
    'Linux',
  ],
  'Databases': [
    'PostgreSQL',
    'MongoDB',
    'Redis',
    'Firebase',
    'Supabase',
    'MySQL',
  ],
  'Design': [
    'UI/UX Design',
    'Figma',
    'Product Design',
    'Graphic Design',
    'Brand Design',
    'Motion Design',
    'User Research',
    'Prototyping',
  ],
  'Business & Marketing': [
    'Product Management',
    'Project Management',
    'Business Development',
    'Sales',
    'Marketing',
    'Growth Hacking',
    'SEO/SEM',
    'Content Marketing',
    'Social Media Marketing',
    'Copywriting',
    'Public Relations',
  ],
  'Finance & Operations': [
    'Financial Modeling',
    'Fundraising',
    'Investor Relations',
    'Accounting',
    'Legal',
    'Operations',
    'Supply Chain',
  ],
  'Leadership': [
    'Team Leadership',
    'Strategic Planning',
    'People Management',
    'Agile/Scrum',
    'Public Speaking',
    'Negotiation',
  ],
  'Emerging Tech': [
    'Blockchain',
    'Web3',
    'Smart Contracts',
    'Cybersecurity',
    'IoT',
    'AR/VR',
    'Hardware',
    'Robotics',
    '3D Printing',
  ],
};

// Interests organized by category
export const INTEREST_CATEGORIES = {
  'Startup Stage': [
    'Early-stage Startups',
    'Seed Stage',
    'Series A+',
    'Bootstrapping',
  ],
  'Industries': [
    'SaaS',
    'Fintech',
    'Healthtech',
    'Edtech',
    'E-commerce',
    'Marketplaces',
    'Consumer Apps',
    'Enterprise Software',
    'Developer Tools',
    'Climate Tech',
    'Clean Energy',
    'Biotech',
    'Gaming',
    'Media & Entertainment',
    'Real Estate Tech',
    'Food & Agriculture',
    'Transportation',
  ],
  'Technologies': [
    'Artificial Intelligence',
    'Machine Learning',
    'Blockchain',
    'Web3 & Crypto',
    'AR/VR',
    'IoT',
    'Robotics',
    'Quantum Computing',
    'Deep Tech',
    'Hardware',
    'Space Tech',
  ],
  'Goals & Roles': [
    'Finding Cofounders',
    'Joining a Startup',
    'Building Side Projects',
    'Mentoring',
    'Being Mentored',
    'Investing',
    'Angel Investing',
    'VC',
    'Freelancing',
    'Consulting',
  ],
  'Community & Events': [
    'Networking',
    'Hackathons',
    'Pitch Competitions',
    'Startup Events',
    'Tech Conferences',
    'Open Source',
    'Writing & Blogging',
    'Podcasting',
    'Community Building',
  ],
  'Growth & Learning': [
    'Entrepreneurship',
    'Product Building',
    'Growth & Scaling',
    'Fundraising',
    'Leadership Development',
    'Career Transitions',
  ],
  'Academic': [
    'Research Commercialization',
    'University Spin-offs',
    'PhD to Industry',
    'Student Ventures',
  ],
};

// Flat lists for backward compatibility
export const SKILL_OPTIONS = Object.values(SKILL_CATEGORIES).flat();
export const INTEREST_OPTIONS = Object.values(INTEREST_CATEGORIES).flat();
