-- First add a unique constraint on domain to avoid duplicates
ALTER TABLE public.universities ADD CONSTRAINT universities_domain_unique UNIQUE (domain);

-- Insert major US universities (avoiding duplicates with ON CONFLICT)
INSERT INTO public.universities (name, short_name, domain) VALUES
-- Ivy League
('Yale University', 'Yale', 'yale.edu'),
('Princeton University', 'Princeton', 'princeton.edu'),
('Brown University', 'Brown', 'brown.edu'),
('Dartmouth College', 'Dartmouth', 'dartmouth.edu'),
('Cornell University', 'Cornell', 'cornell.edu'),
-- Top Private Universities
('Duke University', 'Duke', 'duke.edu'),
('University of Chicago', 'UChicago', 'uchicago.edu'),
('Johns Hopkins University', 'Johns Hopkins', 'jhu.edu'),
('Rice University', 'Rice', 'rice.edu'),
('Vanderbilt University', 'Vanderbilt', 'vanderbilt.edu'),
('Washington University in St. Louis', 'WashU', 'wustl.edu'),
('Emory University', 'Emory', 'emory.edu'),
('University of Notre Dame', 'Notre Dame', 'nd.edu'),
('Georgetown University', 'Georgetown', 'georgetown.edu'),
('Carnegie Mellon University', 'CMU', 'cmu.edu'),
('University of Southern California', 'USC', 'usc.edu'),
('New York University', 'NYU', 'nyu.edu'),
('Boston University', 'BU', 'bu.edu'),
('Boston College', 'BC', 'bc.edu'),
('Tufts University', 'Tufts', 'tufts.edu'),
('Northeastern University', 'Northeastern', 'northeastern.edu'),
('Wake Forest University', 'Wake Forest', 'wfu.edu'),
-- UC System
('University of California, San Diego', 'UCSD', 'ucsd.edu'),
('University of California, Davis', 'UC Davis', 'ucdavis.edu'),
('University of California, Irvine', 'UCI', 'uci.edu'),
('University of California, Santa Barbara', 'UCSB', 'ucsb.edu'),
('University of California, Santa Cruz', 'UCSC', 'ucsc.edu'),
('University of California, Riverside', 'UCR', 'ucr.edu'),
('University of California, Merced', 'UC Merced', 'ucmerced.edu'),
-- Public Flagships
('University of Michigan', 'UMich', 'umich.edu'),
('University of Virginia', 'UVA', 'virginia.edu'),
('University of North Carolina at Chapel Hill', 'UNC', 'unc.edu'),
('University of Texas at Austin', 'UT Austin', 'utexas.edu'),
('University of Wisconsin-Madison', 'UW-Madison', 'wisc.edu'),
('University of Illinois Urbana-Champaign', 'UIUC', 'illinois.edu'),
('Georgia Institute of Technology', 'Georgia Tech', 'gatech.edu'),
('University of Florida', 'UF', 'ufl.edu'),
('Ohio State University', 'Ohio State', 'osu.edu'),
('Pennsylvania State University', 'Penn State', 'psu.edu'),
('University of Washington', 'UW', 'uw.edu'),
('University of Maryland', 'UMD', 'umd.edu'),
('Purdue University', 'Purdue', 'purdue.edu'),
('Indiana University Bloomington', 'IU', 'indiana.edu'),
('University of Minnesota', 'UMN', 'umn.edu'),
('University of Arizona', 'Arizona', 'arizona.edu'),
('Arizona State University', 'ASU', 'asu.edu'),
('University of Colorado Boulder', 'CU Boulder', 'colorado.edu'),
('University of Iowa', 'Iowa', 'uiowa.edu'),
('University of Oregon', 'UO', 'uoregon.edu'),
('Oregon State University', 'Oregon State', 'oregonstate.edu'),
('Michigan State University', 'MSU', 'msu.edu'),
('Virginia Tech', 'Virginia Tech', 'vt.edu'),
('University of Pittsburgh', 'Pitt', 'pitt.edu'),
('Rutgers University', 'Rutgers', 'rutgers.edu'),
('University of Georgia', 'UGA', 'uga.edu'),
('University of Connecticut', 'UConn', 'uconn.edu'),
('University of Massachusetts Amherst', 'UMass', 'umass.edu'),
('University of South Carolina', 'South Carolina', 'sc.edu'),
('University of Tennessee', 'UTK', 'utk.edu'),
('University of Kentucky', 'UK', 'uky.edu'),
('University of Alabama', 'Alabama', 'ua.edu'),
('Auburn University', 'Auburn', 'auburn.edu'),
('Louisiana State University', 'LSU', 'lsu.edu'),
('University of Oklahoma', 'OU', 'ou.edu'),
('University of Kansas', 'KU', 'ku.edu'),
('University of Nebraska-Lincoln', 'Nebraska', 'unl.edu'),
('Iowa State University', 'Iowa State', 'iastate.edu'),
('Kansas State University', 'K-State', 'ksu.edu'),
('Texas A&M University', 'Texas A&M', 'tamu.edu'),
('University of Houston', 'UH', 'uh.edu'),
('Baylor University', 'Baylor', 'baylor.edu'),
('Texas Christian University', 'TCU', 'tcu.edu'),
('Southern Methodist University', 'SMU', 'smu.edu'),
('University of Utah', 'Utah', 'utah.edu'),
('Brigham Young University', 'BYU', 'byu.edu'),
('University of Nevada, Las Vegas', 'UNLV', 'unlv.edu'),
('San Diego State University', 'SDSU', 'sdsu.edu'),
('California State University, Los Angeles', 'Cal State LA', 'calstatela.edu'),
('University of Miami', 'Miami', 'miami.edu'),
('Florida State University', 'FSU', 'fsu.edu'),
('University of Central Florida', 'UCF', 'ucf.edu'),
('University of South Florida', 'USF', 'usf.edu'),
('North Carolina State University', 'NC State', 'ncsu.edu'),
('Clemson University', 'Clemson', 'clemson.edu'),
('Syracuse University', 'Syracuse', 'syr.edu'),
('University of Rochester', 'Rochester', 'rochester.edu'),
('Rensselaer Polytechnic Institute', 'RPI', 'rpi.edu'),
('Brandeis University', 'Brandeis', 'brandeis.edu'),
('Case Western Reserve University', 'Case Western', 'case.edu'),
('Tulane University', 'Tulane', 'tulane.edu'),
('George Washington University', 'GWU', 'gwu.edu'),
('American University', 'American', 'american.edu'),
('Fordham University', 'Fordham', 'fordham.edu'),
('Villanova University', 'Villanova', 'villanova.edu'),
('Santa Clara University', 'Santa Clara', 'scu.edu'),
('Loyola Marymount University', 'LMU', 'lmu.edu'),
('Pepperdine University', 'Pepperdine', 'pepperdine.edu'),
('California Institute of Technology', 'Caltech', 'caltech.edu'),
('Howard University', 'Howard', 'howard.edu'),
('Spelman College', 'Spelman', 'spelman.edu'),
('Morehouse College', 'Morehouse', 'morehouse.edu'),
('University of Delaware', 'Delaware', 'udel.edu'),
('University of New Hampshire', 'UNH', 'unh.edu'),
('University of Vermont', 'Vermont', 'uvm.edu'),
('University of Maine', 'Maine', 'maine.edu'),
('University of Rhode Island', 'URI', 'uri.edu'),
('West Virginia University', 'WVU', 'wvu.edu'),
('University of Arkansas', 'Arkansas', 'uark.edu'),
('University of Mississippi', 'Ole Miss', 'olemiss.edu'),
('Mississippi State University', 'Miss State', 'msstate.edu'),
('University of New Mexico', 'UNM', 'unm.edu'),
('New Mexico State University', 'NMSU', 'nmsu.edu'),
('University of Nevada, Reno', 'UNR', 'unr.edu'),
('University of Idaho', 'Idaho', 'uidaho.edu'),
('Boise State University', 'Boise State', 'boisestate.edu'),
('University of Wyoming', 'Wyoming', 'uwyo.edu'),
('Montana State University', 'Montana State', 'montana.edu'),
('University of Montana', 'Montana', 'umt.edu'),
('University of North Dakota', 'UND', 'und.edu'),
('North Dakota State University', 'NDSU', 'ndsu.edu'),
('University of South Dakota', 'USD', 'usd.edu'),
('South Dakota State University', 'SDSU', 'sdstate.edu'),
('Colorado State University', 'CSU', 'colostate.edu'),
('University of Denver', 'DU', 'du.edu'),
('Marquette University', 'Marquette', 'marquette.edu'),
('DePaul University', 'DePaul', 'depaul.edu'),
('Loyola University Chicago', 'Loyola Chicago', 'luc.edu'),
('University of Illinois Chicago', 'UIC', 'uic.edu'),
('Illinois State University', 'Illinois State', 'ilstu.edu'),
('Southern Illinois University', 'SIU', 'siu.edu'),
('Ball State University', 'Ball State', 'bsu.edu'),
('University of Cincinnati', 'Cincinnati', 'uc.edu'),
('Miami University', 'Miami OH', 'miamioh.edu'),
('Kent State University', 'Kent State', 'kent.edu'),
('Bowling Green State University', 'BGSU', 'bgsu.edu'),
('Temple University', 'Temple', 'temple.edu'),
('Drexel University', 'Drexel', 'drexel.edu'),
('University at Buffalo', 'UB', 'buffalo.edu'),
('Stony Brook University', 'Stony Brook', 'stonybrook.edu'),
('Binghamton University', 'Binghamton', 'binghamton.edu'),
('University at Albany', 'Albany', 'albany.edu'),
('CUNY Hunter College', 'Hunter', 'hunter.cuny.edu'),
('CUNY Baruch College', 'Baruch', 'baruch.cuny.edu'),
('CUNY City College', 'CCNY', 'ccny.cuny.edu'),
('Hofstra University', 'Hofstra', 'hofstra.edu'),
('St. Johns University', 'St Johns', 'stjohns.edu'),
('Seton Hall University', 'Seton Hall', 'shu.edu'),
('Stevens Institute of Technology', 'Stevens', 'stevens.edu'),
('New Jersey Institute of Technology', 'NJIT', 'njit.edu'),
('University of Hartford', 'Hartford', 'hartford.edu'),
('Sacred Heart University', 'Sacred Heart', 'sacredheart.edu'),
('Quinnipiac University', 'Quinnipiac', 'quinnipiac.edu'),
('Fairfield University', 'Fairfield', 'fairfield.edu'),
('University of Dayton', 'Dayton', 'udayton.edu'),
('Xavier University', 'Xavier', 'xavier.edu'),
('Creighton University', 'Creighton', 'creighton.edu'),
('University of Tulsa', 'Tulsa', 'utulsa.edu'),
('Oklahoma State University', 'Oklahoma State', 'okstate.edu'),
('Texas Tech University', 'Texas Tech', 'ttu.edu'),
('University of North Texas', 'UNT', 'unt.edu'),
('Texas State University', 'Texas State', 'txstate.edu'),
('Sam Houston State University', 'SHSU', 'shsu.edu'),
('University of Texas at San Antonio', 'UTSA', 'utsa.edu'),
('University of Texas at Dallas', 'UTD', 'utdallas.edu'),
('University of Texas at Arlington', 'UTA', 'uta.edu'),
('University of Texas at El Paso', 'UTEP', 'utep.edu'),
('California Polytechnic State University', 'Cal Poly', 'calpoly.edu'),
('California State University, Fullerton', 'Cal State Fullerton', 'fullerton.edu'),
('California State University, Long Beach', 'CSULB', 'csulb.edu'),
('California State University, Northridge', 'CSUN', 'csun.edu'),
('San Jose State University', 'SJSU', 'sjsu.edu'),
('San Francisco State University', 'SFSU', 'sfsu.edu'),
('Sacramento State University', 'Sac State', 'csus.edu'),
('Fresno State University', 'Fresno State', 'fresnostate.edu'),
('University of San Francisco', 'USF', 'usfca.edu'),
('Santa Clara University', 'SCU', 'scu.edu'),
('Chapman University', 'Chapman', 'chapman.edu'),
('Loyola Marymount University', 'LMU', 'lmu.edu'),
('Gonzaga University', 'Gonzaga', 'gonzaga.edu'),
('Seattle University', 'Seattle U', 'seattleu.edu'),
('Portland State University', 'Portland State', 'pdx.edu'),
('University of Portland', 'Portland', 'up.edu'),
('Washington State University', 'WSU', 'wsu.edu'),
('University of Hawaii at Manoa', 'Hawaii', 'hawaii.edu'),
('University of Alaska Fairbanks', 'Alaska', 'alaska.edu')
ON CONFLICT (domain) DO NOTHING;